#![expect(clippy::print_stdout, reason = "binary")]
use std::collections::HashMap;
use std::fs;
use std::path::Path;

const ROOT: &str = "/usr/share/zoneinfo/posix/";

fn main() {
	// add bmt zone
	print!("// @generated by gentz\ntzabbr={{\"Europe/Biel\":{{\"3600\":\"BMT\"}}");
	collect(Path::new(ROOT));
	println!("}}");
}

fn collect(dir: &Path) {
	for file in fs::read_dir(dir).unwrap() {
		let file = file.unwrap();
		let ty = file.file_type().unwrap();
		if ty.is_dir() {
			collect(&file.path());
		} else if !ty.is_dir() {
			write_zone(&file.path());
		} else {
			panic!("symlink");
		}
	}
}

fn write_zone(path: &Path) {
	print!(",");
	let name = path.strip_prefix(ROOT).unwrap().to_str().unwrap();
	let zone = zoneinfo_compiled::parse(fs::read(path).unwrap())
		.unwrap()
		.time_zone
		.fixed_timespans;
	let mut map = HashMap::new();
	for span in [zone.first]
		.into_iter()
		.chain(zone.rest.into_iter().map(|(_, zone)| zone))
	{
		assert!(span.name.len() <= 5, "bad zone name");
		map.insert(span.offset, span.name);
	}
	print!("{name:?}:{{");
	let mut comma = false;
	for (k, v) in map {
		if comma {
			print!(",");
		}
		comma = true;
		print!("\"{k}\":{v:?}");
	}
	print!("}}");
}
